export interface Order {
    order_id: string,
    parent_order_id: string,
    exchange_order_id: string,
    placed_by: string,
    variety: string,
    status: string,
    tradingsymbol: string,
    exchange: string,
    instrument_token: string,
    transaction_type: string,
    order_type: string,
    product: string,
    validity: string,
    price: number,
    quantity: number,
    trigger_price: number,
    average_price: number,
    peding_quantity: number,
    filled_quantity: number,
    disclosed_quantity: number,
    order_timestamp: string,
    exchange_timestamp: string,
    exchange_update_timestamp: string,
    status_message: string,
    meta: string,
}